description: "Vex: some ruby extensions"
url: http://github.com/pboy/vex  
author: pboy
email: eno-pboy@open-lab.org  
ignore_pattern:
  - "tmp/*"
  - "test/tmp/*"
  - "test/*.sqlite3*"
  - "**/.*"
  - "vex.tmproj"
  
